# Generated by Django 5.0.1 on 2024-03-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='p_name',
            field=models.CharField(max_length=255),
        ),
    ]
